/* Bar functionality */
#include "bar_indicators.h"
#include "bar_tagicons.h"
#include "bar.h"

#include "combo.h"
#include "bar_ltsymbol.h"
#include "bar_status.h"
#include "bar_tags.h"
#include "bar_wintitle.h"
#include "bar_awesomebar.h"
#include "bar_systray.h"
#include "bar_wintitleactions.h"

/* Other patches */
#include "autostart.h"
#include "cfacts.h"
#include "cyclelayouts.h"
#include "decorationhints.h"
#include "dragcfact.h"
#include "dragmfact.h"
#include "dwmc.h"
#include "fakefullscreenclient.h"
#include "mpdcontrol.h"
#include "pertag.h"
#include "placedir.h"
#include "placemouse.h"
#include "renamed_scratchpads.h"
#include "shift.h"
#include "shiftboth.h"
#include "shiftviewclients.h"
#include "sizehints_ruled.h"
#include "swallow.h"
#include "tapresize.h"
#include "togglefullscreen.h"
#include "toggletopbar.h"
#include "vanitygaps.h"
#include "zoomswap.h"
/* Layouts */
#include "layout_bstack.h"
#include "layout_deck.h"
#include "layout_fibonacci.h"
#include "layout_flextile-deluxe.h"
#include "layout_monocle.h"
#include "layout_tile.h"

