/* Bar functionality */
#include "bar_indicators.c"
#include "bar_tagicons.c"
#include "bar.c"

#include "combo.c"
#include "bar_ltsymbol.c"
#include "bar_status.c"
#include "bar_tags.c"
#include "bar_wintitle.c"
#include "bar_awesomebar.c"
#include "bar_systray.c"
#include "bar_wintitleactions.c"

/* Other patches */
#include "autostart.c"
#include "cfacts.c"
#include "cyclelayouts.c"
#include "decorationhints.c"
#include "dragcfact.c"
#include "dwmc.c"
#include "fakefullscreenclient.c"
#include "mpdcontrol.c"
#include "pertag.c"
#include "placedir.c"
#include "placemouse.c"
#include "renamed_scratchpads.c"
#include "shift.c"
#include "shiftboth.c"
#include "shiftviewclients.c"
#include "sizehints_ruled.c"
#include "swallow.c"
#include "tapresize.c"
#include "togglefullscreen.c"
#include "toggletopbar.c"
#include "vanitygaps.c"
#include "zoomswap.c"
#include "dragmfact.c"
/* Layouts */
#include "layout_facts.c"
#include "layout_bstack.c"
#include "layout_deck.c"
#include "layout_fibonacci.c"
#include "layout_flextile-deluxe.c"
#include "layout_monocle.c"
#include "layout_tile.c"

